### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by friskfly** [Gottox/child_pty#13]
MacOS EI   

```
> child_pty@3.0.0 install /Users/FX/Source/node-automate-examples/node_modules/child_pty
> node-gyp rebuild

  CXX(target) Release/obj.target/exechelper/src/exechelper.o
  LINK(target) Release/exechelper
  CXX(target) Release/obj.target/pty/src/pty.o
../src/pty.cpp:15:12: fatal error: '/usr/include/util.h' file not found
#               include </usr/include/util.h>
                        ^
1 error generated.
make: *** [Release/obj.target/pty/src/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:88:13)
gyp ERR! stack     at ChildProcess.emit (events.js:173:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/FX/Source/node-automate-examples/node_modules/child_pty
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

**Comment by friskfly** [comment]
The latest commit fixed this bug.  Can you update to npm ?

**Comment by Gottox** [comment]
can you check the v3.0 branch too?

**Comment by Gottox** [comment]
released, have fun :)
