### ISSUE TITLE
Setting stdin to pipe fails..

### ISSUE THREAD

**Issue by ioquatix** [Gottox/child_pty#22]
It looks like something is wrong here. When stdio: ['pipe', 'pty', 'pty'] I got error EFAULT.

```javascript
	// set up message receiver on the client
	child.stdio.pop().once('data', function(data) {
		var err, errno = - data.readInt32BE(0);
		if(util._errnoException)
			err = util._errnoException(errno, 'spawn ' + command);
		else
			err = new Error('spawn ' + command + ' ' + errno);
		err.path = command;
		err.spawnargs = args.slice(2);
		child.emit('error', err);
		child.removeAllListeners();
		child.kill();
	});
```

**Comment by ioquatix** [comment]
FYI, here is my exact line of code:

    @child = ChildPTY.spawn(args[0], args.slice(1), cwd: cwd, env: env, stdio: ['pipe', 'pty', 'pty'])

**Comment by ioquatix** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: linux 4.8.12-2-ARCH
**Thrown From**: [script-runner](https://github.com/ioquatix/script-runner) package, v2.0.0


### Stack Trace

Uncaught Error: spawn /usr/bin/env EFAULT

```
At events.js:160

Error: spawn /usr/bin/env EFAULT
    at Object.exports._errnoException (util.js:1026:11)
    at Socket.<anonymous> (/home/samuel/.atom/packages/script-runner/node_modules/child_pty/lib/child_pty.js:108:15)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
  2x -6:29.9.0 run:script (atom-text-editor.editor.is-focused)
     -4:55.6.0 core:delete (atom-text-editor.editor.is-focused)
     -4:55.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:42.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:cut (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:00.2.0 run:script (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace",
      "autoflow",
      "autosave",
      "autocomplete",
      "autocomplete-clang",
      "symbols-view"
    ],
    "excludeVcsIgnoredPaths": false,
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "script-runner": {
    "theme": "dark"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v5.0.0 (active)
atom-dark-ui-slim, v0.47.1 (inactive)
atom-soda-dark-ui, v1.1.0 (inactive)
atom-solo-dark-ui, v1.3.0 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-ctags, v0.4.1 (active)
color-picker, v2.2.3 (active)
editor-stats, v0.17.0 (active)
file-icons, v1.7.25 (active)
git-blame, v0.4.11 (inactive)
git-plus, v5.28.0 (active)
imdone-atom, v2.0.19 (active)
imdone-atom-github, v0.1.11 (active)
language-latex, v1.0.0 (active)
language-openscad, v0.4.3 (active)
language-trenni, v0.2.1 (active)
latex, v0.41.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
paraiso-dark, v1.3.1 (inactive)
pdf-view, v0.53.0 (active)
rspec, v0.3.2 (inactive)
script-runner, v2.0.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-dark-ui, v0.3.1 (inactive)
solarized-light-ui, v0.1.0 (inactive)
sync-settings, v0.8.0 (active)
tabs-to-spaces, v1.0.2 (active)
travis-ci-status, v1.3.0 (active)
unity-dark-ui, v2.0.9 (inactive)
web-browser, v1.5.0 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Gottox** [comment]
Thanks for this report. I'm able to reproduce this issue.

**Comment by ioquatix** [comment]
Thanks looking forward to an updaye

**Comment by ioquatix** [comment]
Is the `exechelper` really necessary? Couldn't you do most of the work in `NAN_METHOD(Open)` in pty.cpp?

**Comment by Gottox** [comment]
Unfortunately, yes it is neccassary. You have to call TIOCSCTTY to set the controlling pty after the new process is forked. And as forking/executing is done by node and we cannot hook anything in between fork and exec I have to use this wrapper.

Actually that's the problem why your program does not work: I foolishly assumed, that stdin is always the pty which isn't true for your case.

I'm unavailable at the weekend, so expect a fix at sunday.

**Comment by derhuerst** [comment]
bump. (:

**Comment by Gottox** [comment]
463f063e8a559c9e0f4e2d8596c64addcec8cafe fixed, please test 3.0.5

**Comment by ioquatix** [comment]
Awesome :)

**Comment by Gottox** [comment]
Damn, give me a sec and wait for 3.0.6 :D

**Comment by Gottox** [comment]
done, please check and reopen if anything fails! Sorry for the long delay!
