### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by tasoss** [Gottox/child_pty#26]
Hello.
Thanks for child_pty. 
It's the best among the others that can be found via npm.
I get an deprecation warning and i was wondering if you could fix it.
Thanks!

> [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:127:12)
    at Object.fs.close (fs.js:607:20)
    at Object.module.exports.spawn (/home/tasoss/tsat/StreamManager/Scanner/node_modules/child_pty/lib/child_pty.js:95:5)

**Comment by Gottox** [comment]
Thanks!
