### ISSUE TITLE
ERR_INVALID_CALLBACK

### ISSUE THREAD

**Issue by alexktchen** [Gottox/child_pty#31]
Hi, when I call var pty = child_pty.spawn('ls', []);
I aways got ERR_INVALID_CALLBACK error, I have deploy the node JS on AWS container.
Have some one can look on this?

fs.js:167
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.close (fs.js:540:20)
    at Object.module.exports.spawn (/app/dv-webterm/node_modules/child_pty/lib/child_pty.js:95:5)
    at Socket.<anonymous> (/app/app.js:54:24)
    at Socket.onstream (/app/node_modules/socket.io-stream/lib/socket.js:184:14)
    at Socket.emit (events.js:182:13)
    at Socket.<anonymous> (/app/node_modules/component-bind/index.js:21:15)
    at Socket.emit (events.js:182:13)
    at /app/dv-webterm/node_modules/socket.io/lib/socket.js:503:12
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by yourimiyi** [comment]
Same issue, NodeJS 10+
/node_modules/child_pty/lib/child_pty.js:95:5  -- fs.close function call, without callback function.

change `fs.close` to `fs.closeSync` or add empty callback function. `fs.close(..., () =>true)`

**Comment by Birkenstab** [comment]
The commit abbe41e has already fixed this but it is not yet published on npm
