### ISSUE TITLE
Doesn't work with Atom-shell / Electron

### ISSUE THREAD

**Issue by cronvel** [Gottox/child_pty#6]
Hi,

If it try the example in the README.md, I got this strange error:

```
$ ./node_modules/electron-prebuilt/dist/electron test.js 
[17962:0515/172530:ERROR:browser_main_loop.cc(171)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App threw an error when running [Error: Module did not self-register.]
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Module did not self-register.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:134:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:134:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Module.require (module.js:353:17)
    at require (module.js:372:17)
    at Object.<anonymous> (/home/cedric/inside/soulserv/tterm/node_modules/child_pty/lib/child_pty.js:1:73)
    at Module._compile (module.js:418:26)
    at Object.Module._extensions..js (module.js:436:10)
```
In fact, just requiring the lib cause this.

I believe Electron use IO.js.

Here is the `process.versions`:
```
{ http_parser: '2.3.0',
  node: '1.6.3',
  v8: '4.2.77.15',
  uv: '1.4.2',
  zlib: '1.2.8',
  ares: '1.10.0-DEV',
  modules: '43',
  openssl: '1.0.1m',
  electron: '0.26.0',
  'atom-shell': '0.26.0',
  chrome: '42.0.2311.107' }
```

Any idea?

**Comment by Gottox** [comment]
How did you compile child_pty for electron? Is there anything like node-gyp or nw-gyp?

**Comment by cronvel** [comment]
Hi,
I used *electron-rebuild*.
I'm trying to figure out if it's a problem with child_pty or electron-rebuild ATM. 
Sorry, I have probably filled a false bug report.
I will come back when I will have more informations ;)

**Comment by cronvel** [comment]
Okey, I found one issue with *electron-rebuild* when no argument is supplied.

Now I'm passing arguments explicitly:
./node_modules/.bin/electron-rebuild -v 0.26.0 -m node_modules

Again, sorry for the false positive.
